CustomizableWeaponry:addFireSound("CW_FAS2_SKS_FIRE", "weapons/sks/sks_fire1.wav", 1, 115, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_FAS2_SKS_FIRE_SUPP", "weapons/sks/sks_suppressed_fire1.wav", 1, 95, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_FAS2_SKS_BOLTBACK", "weapons/sks/sks_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_SKS_BOLTFORWARD", "weapons/sks/sks_boltforward.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_SKS_BOLTRELEASE", "weapons/sks/sks_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_SKS_CLIPIN", "weapons/sks/sks_clipin.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_SKS_INSERTNOMEN", "weapons/sks/sks_insert_nomen.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_SKS_INSERT1", "weapons/sks/sks_insert1.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_SKS_INSERT2", "weapons/sks/sks_insert2.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_SKS_INSERT3", "weapons/sks/sks_insertlast.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_SKS_LATCHOPEN", "weapons/sks/sks_latchopen.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_SKS_LATCHCLOSE", "weapons/sks/sks_latchclose.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_SKS_MAGOUT", "weapons/sks/sks_magout.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_SKS_MAGOUT_EMPTY", "weapons/sks/sks_magout_empty.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_SKS_MAGIN", "weapons/sks/sks_magin.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_SKS_REMOVECLIP", "weapons/sks/sks_removeclip.wav")
