CustomizableWeaponry:addFireSound("CW_FAS2_M60_FIRE", "weapons/m60/m60_fire1.wav", 1, 115, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_FAS2_M60_FIRE_SUPP", "weapons/m60/m60_suppressed_fire1.wav", 1, 95, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_FAS2_M60_BELTINSERT", "weapons/m60/m60_belt_insert.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_BELTREMOVE", "weapons/m60/m60_belt_remove.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_BELT", {"weapons/m60/m60_belt1.wav", "weapons/m60/m60_belt2.wav", "weapons/m60/m60_belt3.wav", "weapons/m60/m60_belt4.wav"})
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_BIPOD", "weapons/m60/m60_bipod.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_CARDBOARDINSERT", "weapons/m60/m60_cardboard_insert.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_CARDBOARDREMOVE", "weapons/m60/m60_cardboard_remove.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_CARDBOARDREMOVE_FULL", "weapons/m60/m60_cardboard_remove_full.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_CARDBOARDRIP", {"weapons/m60/m60_cardboard_rip1.wav", "weapons/m60/m60_cardboard_rip2.wav"})
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_BIPOD", "weapons/m60/m60_bipod.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_CARRYINGHANDLE", "weapons/m60/m60_carryinghandle.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_CHARGE", "weapons/m60/m60_charge.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_CLOSE", "weapons/m60/m60_close.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_FEEDINGMECHANISM", "weapons/m60/m60_feeding_mechanism.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_FEEDINGTRAY", "weapons/m60/m60_feeding_tray.wav")
-- CustomizableWeaponry:addReloadSound("CW_FAS2_M60_FLIPSIGHTS", "weapons/m60/m60_flipsights.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_OPEN", "weapons/m60/m60_open.wav")
-- CustomizableWeaponry:addReloadSound("CW_FAS2_M60_SHOULDERREST", "weapons/m60/m60_shoulderrest.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_STARTERTAB", "weapons/m60/m60_startertab.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_VELCROCLOSE", "weapons/m60/m60_velcro_close.wav")
CustomizableWeaponry:addReloadSound("CW_FAS2_M60_VELCRORIP", {"weapons/m60/m60_velcro_rip1.wav", "weapons/m60/m60_velcro_rip2.wav"})
