-- damn thats a lotta shells
CustomizableWeaponry.shells:addNew("50bmg", "models/shells/50bmg.mdl", "CW_SHELL_MAIN")
CustomizableWeaponry.shells:addNew("50beowulf", "models/shells/50bmg.mdl", "CW_SHELL_MAIN")
CustomizableWeaponry.shells:addNew("762x39", "models/shells/7_62x39mm.mdl", "CW_SHELL_MAIN")
CustomizableWeaponry.shells:addNew("762x39_live", "models/shells/7_62x39mm_live.mdl", "CW_SHELL_MAIN")
CustomizableWeaponry.shells:addNew("556x45", "models/shells/5_56x45mm.mdl", "CW_SHELL_MAIN")
CustomizableWeaponry.shells:addNew("762x51", "models/shells/7_62x51mm.mdl", "CW_SHELL_MAIN")
CustomizableWeaponry.shells:addNew("545x39", "models/shells/5_45x39mm.mdl", "CW_SHELL_MAIN")
CustomizableWeaponry.shells:addNew("10x25", "models/shells/10x25mm.mdl", "CW_SHELL_SMALL")
CustomizableWeaponry.shells:addNew("357sig", "models/shells/357sig.mdl", "CW_SHELL_SMALL")
CustomizableWeaponry.shells:addNew("380acp", "models/shells/380acp.mdl", "CW_SHELL_SMALL")
CustomizableWeaponry.shells:addNew("45acp", "models/shells/45acp.mdl", "CW_SHELL_SMALL")
CustomizableWeaponry.shells:addNew("454casull", "models/shells/454casull.mdl", "CW_SHELL_SMALL")
CustomizableWeaponry.shells:addNew("9x18", "models/shells/9x18mm.mdl", "CW_SHELL_SMALL")
CustomizableWeaponry.shells:addNew("50ae", "models/shells/50ae.mdl", "CW_SHELL_SMALL")
CustomizableWeaponry.shells:addNew("44mag", "models/shells/44mag.mdl", "CW_SHELL_SMALL")
CustomizableWeaponry.shells:addNew("9x19", "models/shells/9x19mm.mdl", "CW_SHELL_SMALL")
CustomizableWeaponry.shells:addNew("357mag", "models/shells/357mag.mdl", "CW_SHELL_SMALL")
CustomizableWeaponry.shells:addNew("9x19", "models/shells/9x19mm.mdl", "CW_SHELL_SMALL")
CustomizableWeaponry.shells:addNew("stripper", "models/shells/sks_clip.mdl", "CW_SHELL_SMALL")
CustomizableWeaponry.shells:addNew("23x75", "models/shells/23mm.mdl", "CW_SHELL_SHOT")
CustomizableWeaponry.shells:addNew("12g_buck", "models/shells/12g_buck.mdl", "CW_SHELL_SHOT")
-- CustomizableWeaponry.shells:addNew("12g_slug", "models/shells/12g_slug.mdl", "CW_SHELL_SHOT")
